services:
  postgres:
    image: postgres:17-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data      
    ports:
      - '6379:6379'

  api:
    build: . 
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env_docker

volumes:
  postgres:
  redis: